apiVersion: v1
kind: Config
clusters:
- name: "hw3finalangular"
  cluster:
    server: "https://18.232.73.115/k8s/clusters/c-vnzvh"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ2akNDQ\
      VdPZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQkdNUnd3R2dZRFZRUUtFeE5rZVc1aGJXbGoKY\
      kdsemRHVnVaWEl0YjNKbk1TWXdKQVlEVlFRRERCMWtlVzVoYldsamJHbHpkR1Z1WlhJdFkyRkFNV\
      FkyT0RZeQpPRGMxTkRBZUZ3MHlNakV4TVRZeE9UVTVNVFJhRncwek1qRXhNVE14T1RVNU1UUmFNR\
      Vl4SERBYUJnTlZCQW9UCkUyUjVibUZ0YVdOc2FYTjBaVzVsY2kxdmNtY3hKakFrQmdOVkJBTU1IV\
      1I1Ym1GdGFXTnNhWE4wWlc1bGNpMWoKWVVBeE5qWTROakk0TnpVME1Ga3dFd1lIS29aSXpqMENBU\
      VlJS29aSXpqMERBUWNEUWdBRTlpT3hSVkZtTlpHeAo0ZU1yb05Jekt5bVlXMnpkTEZOcVhHTzc2a\
      lFNSUEzckVSdzZoMWsrajd3R2UwQWtCOHBsQXo0Q2FJNkl0OVh3CnVSZHJBVDg1Z2FOQ01FQXdEZ\
      1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWUQKVlIwT0JCWUVGS\
      UNEK2FwN2hsbE5sWC9NOXgyVHlCVDArMkNnTUFvR0NDcUdTTTQ5QkFNQ0Ewa0FNRVlDSVFDSApnO\
      HVkc3JxVjl0bmtHUll6b2o0akp5M0lGZWFZa1NhTCtKMFZqeVFPdmdJaEFLMTJiSStUcGI3ejFLN\
      HpDU3lBCjF4U1FwMzFkL0s5eERESHRHSzdMU1cvTgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t"
- name: "hw3finalangular-hw3finalangular1"
  cluster:
    server: "https://54.87.192.249:6443"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM0VENDQ\
      WNtZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFTTVJBd0RnWURWUVFERXdkcmRXSmwKT\
      FdOaE1CNFhEVEl5TVRFeE5qSXdNVEExTVZvWERUTXlNVEV4TXpJd01UQTFNVm93RWpFUU1BNEdBM\
      VVFQXhNSAphM1ZpWlMxallUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ\
      0VCQUxONVIxZFFlQUJKCkdTM2ZJRWxEV2t6NWlvNzdhK2wzdVFhOThjQlp3RHY0czZGcUVGY1pEL\
      05BOFZ3TUJ6OHZKYnNidFlPTWFZWCsKd1BkSGUrd3NGUnhXWFJoaHFVZjJkOFVodUxsQWErNWllW\
      nM4dDZxR1JiV0s2WFNjRHlxOXE0UEw5RHFKZFBUUgpkU3NmVitmdVNmc0R1b0VicisxRGpkczA2Z\
      lJhUkZGbVFoT200TmdUYmVLZHlERitCaU5MOXZWcEJNdVNySnBDClNQckdZWVVMcWo0SnNyNEt3M\
      mJxVkNCVnE4UHd0WUhEMHVDM1Y0UDlLSlpocFVKeENGc0ZTQWlmUzFESU1QWWwKVC83aXo0Vms3N\
      GZmWTIzYitFZGhnZG9WcE1kbVpRM2U1MWttUm93c28wanI5M1pEdm5rWlBlR1RsV3BtN0hGbQpHe\
      Wxmb1hNb3ROVUNBd0VBQWFOQ01FQXdEZ1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93U\
      UZNQU1CCkFmOHdIUVlEVlIwT0JCWUVGR3pZMDA5UzBLeDJIQ2Q0ekNyZGtZcDAwbmZZTUEwR0NTc\
      UdTSWIzRFFFQkN3VUEKQTRJQkFRQlZLN3RVUm5BaHJzS3R6bThrWFZ4R1JJdlhNVC81c0dCZHdDd\
      1IvQmtlZCs1SkxnMlhFb3B0cGhXTApyWEczMFJsWGwyamZWZHRQbXo0M2dmeXhWSGRkNjRyYnlze\
      WVLYWc1aU5FU1hINHEzOEJKaFh0QVJKUCszdjh2ClZTOVpCclZsNFo4SlBBK0JoWngwRWxPWGpRT\
      TJnUFA3VVYvVlBDaDAvWmtRNTFnWE1aNVdSZVpoL01EclpXT0cKcHRFdVZMcWlsd3ZFQWVJckdKW\
      HZzTWg3Q2h1cHlhYTJPVG5DOCtZM1l6Z2Q5S09yTU9kUTdVWTM4eUFWWnl5QgpuVVBYMk5FSEQ2d\
      lFsNzVKTG9BOGM3SkhQaFJKKzhUNGYxSlp0aEJrL2h0NDFLdERnVlBaSjlzb1lXUjUyWjUyCkRya\
      0taWlBVSitpdzdIekR0blFOL1JvdzVDbHIKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="

users:
- name: "hw3finalangular"
  user:
    token: "kubeconfig-user-gb88xgm6ns:fm97tqf27fvst6jth2vst5h2r788l62cjd9gr94mdtlnfjvp7dm8jd"


contexts:
- name: "hw3finalangular"
  context:
    user: "hw3finalangular"
    cluster: "hw3finalangular"
- name: "hw3finalangular-hw3finalangular1"
  context:
    user: "hw3finalangular"
    cluster: "hw3finalangular-hw3finalangular1"

current-context: "hw3finalangular"
